name: Wiki Sync
on:
  push:
    branches:
      - develop
    paths: [
      'wiki/**'
    ]
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
        - uses: OrlovM/Wiki-Action@v1
          with:
            path: 'wiki'
            token: ${{ secrets.GITHUB_TOKEN }}